name: build-snap

on: [push]

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: rename template to snapcraft.yaml
        run: |
          ls -larth
          cp snap/snapcraft.yaml_template snap/snapcraft.yaml
          uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
      - uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}